[DEFAULT]
name = main

[composite:main]
use = egg:Paste#urlmap
/: ma_version
/healthcheck: ma_healthcheck
/v2.0: ma_api_v2

[pipeline:ma_version]
pipeline = error_trap versionapp

[pipeline:ma_healthcheck]
pipeline = error_trap healthcheckapp

[pipeline:ma_api_v2]
pipeline = error_trap request_id auth api_v2_app

[app:versionapp]
paste.app_factory = monasca_api.app.api:create_version_app

[app:healthcheckapp]
paste.app_factory = monasca_api.app.api:create_healthcheck_app

[app:api_v2_app]
paste.app_factory = monasca_api.app.api:create_v2_app

[filter:auth]
paste.filter_factory = keystonemiddleware.auth_token:filter_factory

[filter:request_id]
paste.filter_factory = oslo_middleware.request_id:RequestId.factory

# NOTE(trebskit) this is optional
# insert this into either pipeline to get some WSGI environment debug output
[filter:debug]
paste.filter_factory = oslo_middleware.debug:Debug.factory

[filter:error_trap]
paste.filter_factory = oslo_middleware.catch_errors:CatchErrors.factory

[server:main]
use = egg:gunicorn#main
bind = 127.0.0.1:8070
workers = 9
worker-connections = 2000
worker-class = eventlet
timeout = 30
backlog = 2048
keepalive = 2
proc_name = monasca-api
loglevel = DEBUG
