[DEFAULT]
name = monasca_api

[pipeline:main]
# Add validator in the pipeline so the metrics messages can be validated.
pipeline = instrument auth keystonecontext api

[app:api]
paste.app_factory = monasca_api.api.server:launch

[filter:instrument]
paste.filter_factory = monasca_api.middleware.instrument_filter:filter_factory

[filter:auth]
paste.filter_factory = keystonemiddleware.auth_token:filter_factory

[filter:keystonecontext]
paste.filter_factory = monasca_api.middleware.keystone_context_filter:filter_factory

[server:main]
use = egg:gunicorn#main
host = 127.0.0.1
port = 8082
workers = 1
proc_name = monasca_api
on_starting = monasca_api.api.prometheus_hooks.handle_server_starting
worker_exit = monasca_api.api.prometheus_hooks.handle_worker_exit