[DEFAULT]
#logging, make sure that the user under whom the server runs has permission
#to write to the directory.
log_file=monasca.log
log_dir=/var/log/monasca/
log_level=DEBUG

[dispatcher]
driver = kafka

[kafka]
uri = 192.168.1.191:9092
topic = monasca
max_retry = 1
async = True
compact = False
