[DEFAULT]
queue_driver = kafka

#logging, make sure that the user under whom the server runs has permission
#to write to the directory.
log_file=monasca.log
log_dir=/var/log/monasca/
log_level=DEBUG


#kafka dispatcher parameters
kafka.uri=192.168.1.191:9092
kafka.topic=monasca
kafka.max_retry = 1
kafka.async = True
kafka.compact = False


[pipeline:main]
pipeline = api

[app:api]
paste.app_factory = monasca.api.server:api_app

[filter:login]
use = egg: monasca_api_server#login

[filter:inspector]
use = egg: monasca_api_server#inspector
s1 = ss1
s2 = ss2

[server:main]
use = egg:gunicorn#main
host = 0.0.0.0
port = 9090
workers = 1
proc_name = monasca
