[loggers]
keys = root, sqlalchemy

[handlers]
keys = console, file

[formatters]
keys = generic

[logger_root]
level = DEBUG
handlers = console

[logger_sqlalchemy]
level = INFO
handlers = console, file
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.  (Recommended for production systems.)
propagate=0

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_file]
class=FileHandler
level=DEBUG
formatter=generic
args=('/var/log/monasca/api/monasca-api.log', 'a')

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s
