#!/bin/sh
'/opt/monasca-agent/bin/monasca-setup' \
    -u 'monasca-agent' \
    -p 'password' \
     -s 'monitoring'  \
    --keystone_url %KEYSTONE_AUTH_HOST% \
    --project_name 'mini-mon' \
     --monasca_url %MONASCA_API_URL%  \
     \
     --check_frequency '15'  \
     \
     --log_level 'WARN'  \
    --overwrite \
    --system_only \
    --monasca_statsd_port %MONASCA_STATSD_PORT%
