- hosts: primary
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true

          if [ "{{ neutron }}" -eq 1 ] ; then
              export DEVSTACK_GATE_NEUTRON=1
          fi

          export DEVSTACK_GATE_TEMPEST=1
          if [ "{{ tempest }}" -eq 0 ] ; then
              # Do not run any tempest tests
              export DEVSTACK_GATE_TEMPEST_NOTESTS=1
          fi

          if [ "{{ horizon }}" -eq 0 ] ; then
              export DEVSTACK_LOCAL_CONFIG+=$'\n'"disable_service horizon"
          else
              export DEVSTACK_GATE_HORIZON=1
          fi

          # Keep localrc to be able to set some vars in post_test_hook
          export KEEP_LOCALRC=1
          export ENABLED_SERVICES=tempest
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_EXERCISES=0

          if [ {backend} == "postgresql" ]; then
              export DEVSTACK_GATE_POSTGRES=1
          elif [ {backend} == "postgresql" ]; then
              export DEVSTACK_GATE_POSTGRES=0
          else
              echo "unsupported backend {backend}"
              return 1
          fi

          function gate_hook {
              cd /opt/stack/new/monasca-api/
              ./monasca_tempest_tests/contrib/gate_hook.sh
          }
          export -f gate_hook

          function post_test_hook {
              source $BASE/new/devstack/accrc/admin/admin
              cd /opt/stack/new/monasca-api/
              ./monasca_tempest_tests/contrib/post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
